repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-ast
    -   id: fix-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: end-of-file-fixer

-   repo: https://github.com/psf/black
    rev: 23.10.0
    hooks:
    -   id: black

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.1.0'
  hooks:
    - id: ruff
