name: simdec
channels:
  - conda-forge
dependencies:
  # required
  - python>=3.10
  - numpy
  - pandas
  - salib
  - seaborn
  # Dashboard
  - panel
  - cryptography
  # tests
  - pytest
  - pytest-cov
  # dev
  - pre-commit
  - hatch
  # doc
  - sphinx
  - pydata-sphinx-theme
  - accessible-pygments
  - numpydoc
  - myst-nb
