[build]
  command = "npm run build"
  publish = "dist/pyodide"

[dev]
  ignore = ["dist", ".wasm-build-venv", "panel/data"]
  port = 8888

[build.environment]
  PYTHON_VERSION = "3.11"
  NODE_VERSION = "20"
  CACHE_VERSION = "2"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"

[[headers]]
  for = "/*.whl"
  [headers.values]
    Content-Type = "application/zip"
    Access-Control-Allow-Origin = "*"
